version: 0.1

phases:
#   install:
#     commands:
#       - echo installing nodejs...
#       - curl -sL https://deb.nodesource.com/setup_12.x | bash -
#       - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo  "installing dependencies..."
      - npm install
  build:
    commands:
      - echo "building..."
      - npm run build --if-present
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
